### ISSUE TITLE
1.7.5 update throws `.isAttached is not a function` errors

### ISSUE THREAD

**Issue by EvHaus** [glortho/react-keydown#57]
After upgrading from 1.7.4 to 1.7.5 I've been getting these errors from all components that use `react-keydown`:

```
event_handlers.js:37 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0__lib_dom_helpers__.a.isAttached is not a function
    at HTMLDocument._onClick (event_handlers.js:37)
_onClick @ event_handlers.js:37
```

**Comment by glortho** [comment]
Sorry about that! See if it works now as of 1.7.6

**Comment by EvHaus** [comment]
1.7.6 now causes rendering to completely fail with a new error message:

```
Uncaught ReferenceError: sAttached is not defined
    at eval (dom_helpers.js:82)
    at Object../node_modules/react-keydown/es/lib/dom_helpers.js (app.js:10191)
    at __webpack_require__ (app.js:699)
    at fn (app.js:112)
    at eval (event_handlers.js:6)
    at Object../node_modules/react-keydown/es/event_handlers.js (app.js:10168)
    at __webpack_require__ (app.js:699)
    at fn (app.js:112)
    at eval (class_decorator.js:4)
    at Object../node_modules/react-keydown/es/decorators/class_decorator.js (app.js:10136)
```

**Comment by glortho** [comment]
What the. Sorry, inexcusable. Trying to do too much from phone. Give me an hour or so to get back in the saddle

________________________________

**Comment by EvHaus** [comment]
Thanks so much for the quick responses. Let me know when another version is ready to test.

**Comment by glortho** [comment]
A typo, my apologies! Please try 1.7.7.

**Comment by EvHaus** [comment]
Works like a charm. Thanks!
